soap_client:
  #  alternative_endpoints:
  #    service:
  #      port: http://localhost:8080
  namespaces:
    'http://tempuri.org/': 'App\Models\Calculator'

  destinations_php:
    'App\Models\Calculator': /var/www/html/src/Models/Calculator

  destinations_jms:
    'App\Models\Calculator': /var/www/html/src/Models/Calculator
  metadata:
    'http://www.dneonline.com/calculator.asmx?WSDL': ~
