<?php

namespace App\Service\Container;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\InvalidArgumentException;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class SoapContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = [];
        $this->methodMap = [
            'goetas_webservices.soap.metadata_loader.array' => 'getGoetasWebservices_Soap_MetadataLoader_ArrayService',
        ];
        $this->aliases = [
            'goetas_webservices.soap.metadata_reader' => 'goetas_webservices.soap.metadata_loader.array',
        ];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'Psr\\Container\\ContainerInterface' => true,
            'Symfony\\Component\\DependencyInjection\\ContainerInterface' => true,
            'goetas_webservices.soap.metadata.generator' => true,
            'goetas_webservices.soap.metadata_loader.dev' => true,
            'goetas_webservices.soap.stub.class_writer' => true,
            'goetas_webservices.soap.stub.client_generator' => true,
            'goetas_webservices.wsdl2php.converter.jms' => true,
            'goetas_webservices.wsdl2php.converter.php' => true,
            'goetas_webservices.wsdl2php.event_dispatcher' => true,
            'goetas_webservices.wsdl2php.soap_reader' => true,
            'goetas_webservices.wsdl2php.wsdl_reader' => true,
            'goetas_webservices.xsd2php.class_writer.php' => true,
            'goetas_webservices.xsd2php.converter.jms' => true,
            'goetas_webservices.xsd2php.converter.php' => true,
            'goetas_webservices.xsd2php.naming_convention' => true,
            'goetas_webservices.xsd2php.naming_convention.long' => true,
            'goetas_webservices.xsd2php.naming_convention.short' => true,
            'goetas_webservices.xsd2php.path_generator.jms' => true,
            'goetas_webservices.xsd2php.path_generator.jms.psr4' => true,
            'goetas_webservices.xsd2php.path_generator.php' => true,
            'goetas_webservices.xsd2php.path_generator.php.psr4' => true,
            'goetas_webservices.xsd2php.php.class_generator' => true,
            'goetas_webservices.xsd2php.schema_reader' => true,
            'goetas_webservices.xsd2php.writer.jms' => true,
            'goetas_webservices.xsd2php.writer.php' => true,
            'logger' => true,
        ];
    }

    /*
     * Gets the public 'goetas_webservices.soap.metadata_loader.array' shared service.
     *
     * @return \GoetasWebservices\SoapServices\Metadata\Loader\ArrayMetadataLoader
     */
    protected function getGoetasWebservices_Soap_MetadataLoader_ArrayService()
    {
        return $this->services['goetas_webservices.soap.metadata_loader.array'] = new \GoetasWebservices\SoapServices\Metadata\Loader\ArrayMetadataLoader($this->parameters['goetas_webservices.soap.metadata']);
    }

    /**
     * @return array|bool|float|int|string|\UnitEnum|null
     */
    public function getParameter(string $name)
    {
        if (!(isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters))) {
            throw new InvalidArgumentException(sprintf('The parameter "%s" must be defined.', $name));
        }
        if (isset($this->loadedDynamicParameters[$name])) {
            return $this->loadedDynamicParameters[$name] ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
        }

        return $this->parameters[$name];
    }

    public function hasParameter(string $name): bool
    {
        return isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters);
    }

    public function setParameter(string $name, $value): void
    {
        throw new LogicException('Impossible to call set() on a frozen ParameterBag.');
    }

    public function getParameterBag(): ParameterBagInterface
    {
        if (null === $this->parameterBag) {
            $parameters = $this->parameters;
            foreach ($this->loadedDynamicParameters as $name => $loaded) {
                $parameters[$name] = $loaded ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
            }
            $this->parameterBag = new FrozenParameterBag($parameters);
        }

        return $this->parameterBag;
    }

    private $loadedDynamicParameters = [];
    private $dynamicParameters = [];

    private function getDynamicParameter(string $name)
    {
        throw new InvalidArgumentException(sprintf('The dynamic parameter "%s" must be defined.', $name));
    }

    protected function getDefaultParameters(): array
    {
        return [
            'goetas_webservices.soap.metadata' => [
                'http://www.dneonline.com/calculator.asmx?WSDL' => [
                    'Calculator' => [
                        'CalculatorSoap' => [
                            'operations' => [
                                'Add' => [
                                    'action' => 'http://tempuri.org/Add',
                                    'style' => 'document',
                                    'version' => '1.1',
                                    'name' => 'Add',
                                    'method' => 'add',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\AddInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\AddInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\AddInput',
                                        'parts' => [
                                            'add' => 'Add',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\AddOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\AddOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\AddOutput',
                                        'parts' => [
                                            'addResponse' => 'AddResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                                'Subtract' => [
                                    'action' => 'http://tempuri.org/Subtract',
                                    'style' => 'document',
                                    'version' => '1.1',
                                    'name' => 'Subtract',
                                    'method' => 'subtract',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\SubtractInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\SubtractInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\SubtractInput',
                                        'parts' => [
                                            'subtract' => 'Subtract',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\SubtractOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\SubtractOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\SubtractOutput',
                                        'parts' => [
                                            'subtractResponse' => 'SubtractResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                                'Multiply' => [
                                    'action' => 'http://tempuri.org/Multiply',
                                    'style' => 'document',
                                    'version' => '1.1',
                                    'name' => 'Multiply',
                                    'method' => 'multiply',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\MultiplyInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\MultiplyInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\MultiplyInput',
                                        'parts' => [
                                            'multiply' => 'Multiply',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\MultiplyOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\MultiplyOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\MultiplyOutput',
                                        'parts' => [
                                            'multiplyResponse' => 'MultiplyResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                                'Divide' => [
                                    'action' => 'http://tempuri.org/Divide',
                                    'style' => 'document',
                                    'version' => '1.1',
                                    'name' => 'Divide',
                                    'method' => 'divide',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\DivideInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\DivideInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\DivideInput',
                                        'parts' => [
                                            'divide' => 'Divide',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Messages\\DivideOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope\\Headers\\DivideOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\DivideOutput',
                                        'parts' => [
                                            'divideResponse' => 'DivideResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                            ],
                            'unwrap' => false,
                            'endpoint' => 'http://www.dneonline.com/calculator.asmx',
                            'version' => '1.1',
                        ],
                        'CalculatorSoap12' => [
                            'operations' => [
                                'Add' => [
                                    'action' => 'http://tempuri.org/Add',
                                    'style' => 'document',
                                    'version' => '1.2',
                                    'name' => 'Add',
                                    'method' => 'add',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\AddInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\AddInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\AddInput',
                                        'parts' => [
                                            'add' => 'Add',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\AddOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\AddOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\AddOutput',
                                        'parts' => [
                                            'addResponse' => 'AddResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                                'Subtract' => [
                                    'action' => 'http://tempuri.org/Subtract',
                                    'style' => 'document',
                                    'version' => '1.2',
                                    'name' => 'Subtract',
                                    'method' => 'subtract',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\SubtractInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\SubtractInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\SubtractInput',
                                        'parts' => [
                                            'subtract' => 'Subtract',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\SubtractOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\SubtractOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\SubtractOutput',
                                        'parts' => [
                                            'subtractResponse' => 'SubtractResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                                'Multiply' => [
                                    'action' => 'http://tempuri.org/Multiply',
                                    'style' => 'document',
                                    'version' => '1.2',
                                    'name' => 'Multiply',
                                    'method' => 'multiply',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\MultiplyInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\MultiplyInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\MultiplyInput',
                                        'parts' => [
                                            'multiply' => 'Multiply',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\MultiplyOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\MultiplyOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\MultiplyOutput',
                                        'parts' => [
                                            'multiplyResponse' => 'MultiplyResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                                'Divide' => [
                                    'action' => 'http://tempuri.org/Divide',
                                    'style' => 'document',
                                    'version' => '1.2',
                                    'name' => 'Divide',
                                    'method' => 'divide',
                                    'input' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\DivideInput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\DivideInput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\DivideInput',
                                        'parts' => [
                                            'divide' => 'Divide',
                                        ],
                                    ],
                                    'output' => [
                                        'message_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Messages\\DivideOutput',
                                        'headers_fqcn' => 'App\\Models\\Calculator\\SoapEnvelope12\\Headers\\DivideOutput',
                                        'part_fqcn' => 'App\\Models\\Calculator\\SoapParts\\DivideOutput',
                                        'parts' => [
                                            'divideResponse' => 'DivideResponse',
                                        ],
                                    ],
                                    'fault' => [

                                    ],
                                ],
                            ],
                            'unwrap' => false,
                            'endpoint' => 'http://www.dneonline.com/calculator.asmx',
                            'version' => '1.2',
                        ],
                    ],
                ],
            ],
            'goetas_webservices.soap.config' => [
                'namespaces' => [
                    'http://tempuri.org/' => 'App\\Models\\Calculator',
                ],
                'destinations_php' => [
                    'App\\Models\\Calculator' => '/var/www/html/src/Models/Calculator',
                ],
                'destinations_jms' => [
                    'App\\Models\\Calculator' => '/var/www/html/src/Models/Calculator',
                ],
                'metadata' => [
                    'http://www.dneonline.com/calculator.asmx?WSDL' => NULL,
                ],
                'alternative_endpoints' => [

                ],
                'unwrap_returns' => false,
                'naming_strategy' => 'short',
                'path_generator' => 'psr4',
                'known_locations' => [

                ],
                'aliases' => [

                ],
            ],
            'goetas_webservices.soap.unwrap_returns' => false,
        ];
    }
}
